/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'harry' at '9/28/15 11:49 PM' with Gradle 2.6
 *
 * @author harry, @date 9/28/15 11:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
